//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mods.rc
//
#define IDC_TH_SELCURSOR                101
#define IDD_ABOUT_DLG                   102
#define IDB_BULBS                       102
#define IDB_BULBS_MASK                  103
#define IDB_MAP_TYPES                   104
#define IDB_MAP_TYPES_MASK              105
#define IDC_VERTCONNECTCUR              106
#define IDC_ZOOM                        106
#define IDB_16BUTS_MASK                 106
#define IDC_VERTINSERTCUR               107
#define IDC_MOVE_X                      107
#define IDC_MOVE_Y                      112
#define IDC_PAN                         113
#define IDC_DEL_POINT                   114
#define IDC_ADD_POINT                   115
#define IDC_DRAGCURSOR                  116
#define IDB_DCP                         129
#define IDB_BG_DRAGONEYES               130
#define IDB_TEXLAY_LOGO                 131
#define IDB_MANKUA_LOGO                 136
#define IDD_UVW                         141
#define IDB_UTILETOOL                   156
#define IDB_MASK_UTILETOOL              157
#define IDD_DUMMY                       157
#define IDB_BACKS                       161
#define IDB_BACKS_MASK                  162
#define IDD_NURBS                       163
#define IDD_SM_UTILE                    167
#define IDC_SCALE_Y                     176
#define IDC_SCALE_X                     178
#define IDD_TL_SETUVWATT                185
#define IDD_TL_SETNUM                   192
#define IDD_MAPOPTIONS                  195
#define IDB_TYPES                       200
#define IDD_MAP_ACQUIRE                 201
#define IDD_TL_MAIN                     208
#define IDD_TL_MAPPING                  209
#define IDD_TL_TILING                   210
#define IDD_TL_TOOLS                    211
#define IDD_TL_SPLINE                   212
#define IDD_TL_FREE                     213
#define IDD_TL_PELT                     214
#define IDD_PELT_DLG                    215
#define IDB_PELT                        216
#define IDB_PELT_MASK                   217
#define IDD_TL_FRAME                    218
#define IDB_TL_TOOLBAR                  218
#define IDB_TL_TOOLBAR_MASK             219
#define IDD_TL_DATA                     219
#define IDB_16BUTS                      220
#define IDB_TEXLAY_ATT                  222
#define IDB_TEXLAY_ATT_MASK             224
#define IDD_IO_DLG                      225
#define IDB_TEXLAY2_ABOUT               233
#define IDB_TEXLAY2_ABOUT_DEMO          235
#define IDD_DIALOG1                     236
#define IDC_PICK_MM_NODE                1000
#define IDC_PICK_SURFACE                1001
#define IDC_TL_GROUPS_MENU              1001
#define IDC_SM_NORMALIZED               1002
#define IDC_TWIST_BIAS                  1004
#define IDC_TWIST_BIASSPIN              1006
#define IDC_SM_REVERSE                  1006
#define IDC_TAPER_FROM                  1011
#define IDC_TAPER_TO                    1012
#define IDC_TAPER_FROMSPIN              1013
#define IDC_TAPER_TOSPIN                1014
#define IDC_STRENGTH                    1021
#define IDC_STRENGTHSPIN                1022
#define IDC_AUTHORIZE                   1023
#define IDC_TESSELLATE                  1027
#define IDC_THRESHSPINNER               1031
#define IDC_SMOOTH_THRESHSPIN           1035
#define IDC_TES_EDGE                    1036
#define IDC_SMOOTH_THRESH               1036
#define IDC_TES_CENTER                  1037
#define IDC_TENSIONSPINNER              1038
#define IDC_TENSION                     1039
#define IDC_VERTBREAK                   1043
#define IDD_ATT                         1044
#define IDC_VERTREFINE                  1045
#define IDC_TES_FACE_TRI                1045
#define IDC_TES_FACE_POLY               1047
#define IDD_TEXTURELAYERSMAP            1055
#define IDD_MM_SETNUM                   1056
#define IDC_VERTDELETE                  1062
#define IDC_TINT_MAP                    1063
#define IDC_SMOOTH_GRP1                 1064
#define IDC_SMOOTH_GRP2                 1065
#define IDC_SMOOTH_GRP3                 1066
#define IDC_SMOOTH_GRP4                 1067
#define IDC_SMOOTH_GRP5                 1068
#define IDC_TKU_ABOUT                   1068
#define IDC_SMOOTH_GRP6                 1069
#define IDC_SMOOTH_GRP7                 1070
#define IDC_SMOOTH_GRP8                 1071
#define IDC_SMOOTH_GRP9                 1072
#define IDC_SMOOTH_GRP10                1073
#define IDC_SMOOTH_GRP11                1074
#define IDC_VERT_DELETE                 1075
#define IDC_SMOOTH_GRP12                1075
#define IDC_VERT_CREATE                 1076
#define IDC_SMOOTH_GRP13                1076
#define IDC_VERT_COLLAPSE               1077
#define IDC_SMOOTH_GRP14                1077
#define IDC_SMOOTH_GRP15                1078
#define IDC_VERT_DETACH                 1078
#define IDC_SMOOTH_GRP16                1079
#define IDC_SMOOTH_GRP17                1080
#define IDC_VERT_WELD                   1081
#define IDC_SMOOTH_GRP18                1081
#define IDC_SMOOTH_GRP19                1082
#define IDC_VERT_WELDTOVERT             1082
#define IDC_SMOOTH_GRP20                1083
#define IDC_SMOOTH_GRP21                1084
#define IDC_SMOOTH_GRP22                1085
#define IDC_SMOOTH_GRP23                1086
#define IDC_SMOOTH_GRP24                1087
#define IDC_SMOOTH_GRP25                1088
#define IDC_SPIN                        1088
#define IDC_SMOOTH_GRP26                1089
#define IDC_SPINSPIN                    1089
#define IDC_SMOOTH_GRP27                1090
#define IDC_SMOOTH_GRP28                1091
#define IDC_SMOOTH_GRP29                1092
#define IDC_SMOOTH_GRP30                1093
#define IDC_SMOOTH_GRP31                1094
#define IDC_SMOOTH_GRP32                1095
#define IDC_TENSTEXT                    1096
#define IDC_TAPER_AFFECTREGION          1098
#define IDC_TAPER_SYMMETRY              1107
#define IDC_TWIST_AFFECTREGION          1113
#define IDC_TWIST_TO                    1114
#define IDC_TWIST_TOSPIN                1115
#define IDC_TWIST_FROM                  1116
#define IDC_TWIST_FROMSPIN              1117
#define IDC_TL_ABOUT                    1152
#define IDC_MAP_FIT                     1183
#define IDC_MAP_CENTER                  1184
#define IDC_MAP_VIEWALIGN               1185
#define IDC_MAP_NORMALALIGN             1186
#define IDC_MAP_ALIGN_SEL               1187
#define IDC_MAP_FITREGION               1188
#define IDC_MAP_BITMAPFIT               1189
#define IDC_SMOOTH_AUTO                 1196
#define IDC_SMOOTH_PREVENTINDIRECT      1197
#define IDC_MAP_RESET                   1199
#define IDC_MAP_ACQUIRE                 1200
#define IDC_MM_VIEWUNWRAP               1201
#define IDC_MM_LENGTH                   1202
#define IDC_MM_WIDTH                    1203
#define IDC_CC_Y                        1203
#define IDC_MM_HEIGHT                   1204
#define IDC_MM_LENGTHSPIN               1205
#define IDC_MM_WIDTHSPIN                1206
#define IDC_CC_YSPIN                    1206
#define IDC_MM_HEIGHTSPIN               1207
#define IDC_MM_CCH                      1208
#define IDC_MM_CCHSPIN                  1209
#define IDC_MM_ATT                      1210
#define IDC_MM_ATTSPIN                  1211
#define IDC_MM_ATTON                    1214
#define IDC_MM_AUS                      1215
#define IDC_MM_AUSSPIN                  1216
#define IDC_MM_US                       1217
#define IDC_MM_USSPIN                   1218
#define IDC_MM_AUE                      1219
#define IDC_MM_AUESPIN                  1221
#define IDC_MM_AVS                      1222
#define IDC_MM_AVSSPIN                  1223
#define IDC_MM_AVE                      1224
#define IDC_MM_AVESPIN                  1225
#define IDC_MM_AWS                      1226
#define IDC_MM_AWSSPIN                  1227
#define IDC_MM_AWE                      1228
#define IDC_MM_AWESPIN                  1229
#define IDC_MM_RUV                      1230
#define IDC_MM_RUVSPIN                  1231
#define IDC_TL_SCROLL                   1231
#define IDC_MM_UE                       1232
#define IDC_SUBDIVIDE                   1233
#define IDC_MM_UESPIN                   1233
#define IDC_MM_VS                       1234
#define IDC_MM_VSSPIN                   1235
#define IDC_MM_VE                       1236
#define IDC_STEPS                       1237
#define IDC_MM_VESPIN                   1237
#define IDC_STEPSSPINNER                1238
#define IDC_MM_WS                       1238
#define IDC_TESS_U_SPINNER              1239
#define IDC_MM_WSSPIN                   1239
#define IDC_TESS_U                      1240
#define IDC_MM_WE                       1240
#define IDC_TESS_V_SPINNER              1241
#define IDC_MM_WESPIN                   1241
#define IDC_TESS_V                      1242
#define IDC_MM_FS                       1242
#define IDC_TESS_DIST_SPINNER           1243
#define IDC_MM_FSSPIN                   1243
#define IDC_TESS_DIST                   1244
#define IDC_TESS_ANG_SPINNER            1245
#define IDC_TESS_ANG                    1246
#define IDC_TESS_EDGE_SPINNER           1247
#define IDC_TESS_EDGE                   1248
#define IDC_VERT_HIDE                   1252
#define IDC_VERT_UNHIDEALL              1253
#define IDC_SPLINE_VERT_COUNT           1259
#define IDC_SPLINE_VERT_COUNT_TITLE     1260
#define IDC_TENSIONSPIN                 1266
#define IDS_MIRROR_X                    1277
#define IDS_MIRROR_Y                    1278
#define IDS_MIRROR_Z                    1279
#define IDS_MIRROR_XY                   1280
#define IDS_MIRROR_YZ                   1281
#define IDS_MIRROR_ZX                   1282
#define IDC_UNWRAP_EDIT                 1287
#define IDC_UNWARP_TOOLBAR              1288
#define IDC_UNWRAP_RESET                1288
#define IDC_UNWRAP_VIEW                 1290
#define IDC_UNWRAP_LINECOLOR            1291
#define IDC_UNWRAP_XOR                  1292
#define IDC_UNWRAP_SELCOLOR             1293
#define IDC_UNWRAP_CONSTANTUPDATE       1294
#define IDC_UNWRAP_WIDTH                1295
#define IDC_UNWRAP_WIDTHSPIN            1296
#define IDC_UNWRAP_HEIGHT               1297
#define IDC_UNWRAP_HEIGHTSPIN           1298
#define IDC_UNWRAP_DEFAULTS             1299
#define IDC_TESS_VIEW                   1301
#define IDC_TESS_RENDERER               1302
#define IDC_VERT_COPYNS                 1303
#define IDC_TESS_SET                    1303
#define IDC_VERT_PASTENS                1304
#define IDC_TESS_PARAM                  1305
#define IDC_TESS_SPATIAL                1306
#define IDC_TESS_CURV                   1307
#define IDC_TESS_VIEW_DEP               1308
#define IDC_MM_X                        1315
#define IDC_MM_Y                        1316
#define IDC_MM_Z                        1317
#define IDC_UNWRAP_U                    1328
#define IDC_UNWRAP_USPIN                1329
#define IDC_UNWRAP_ULABEL               1330
#define IDC_UNWRAP_V                    1331
#define IDC_UNWRAP_VSPIN                1332
#define IDC_MM_SETNUMBER                1332
#define IDC_UNWRAP_VLABEL               1333
#define IDC_MM_NUMCH                    1333
#define IDC_UNWRAP_W                    1334
#define IDC_MM_NUMCHSPIN                1334
#define IDC_UNWRAP_WSPIN                1335
#define IDC_TL_GMROW                    1335
#define IDC_UNWRAP_WLABEL               1336
#define IDC_TL_GMROW_SPIN               1336
#define IDC_MM_NCH                      1352
#define IDC_SPIN_CH1                    1354
#define IDC_SPIN_CH2                    1355
#define IDC_SPIN_CH3                    1356
#define IDC_SPIN_CH4                    1357
#define IDC_SPIN_CH5                    1358
#define IDC_SPIN_CH6                    1359
#define IDC_TL_NUMMAPS                  1360
#define IDC_EDIT_CH1                    1361
#define IDC_EDIT_CH2                    1362
#define IDC_EDIT_CH3                    1363
#define IDC_EDIT_CH4                    1364
#define IDC_EDIT_CH5                    1365
#define IDC_EDIT_CH6                    1366
#define IDC_TL_BACK1                    1367
#define IDC_TL_BACK2                    1368
#define IDC_TL_BACK3                    1369
#define IDC_TL_CHANAME                  1369
#define IDC_TL_BACK4                    1370
#define IDC_TL_BACK5                    1371
#define IDC_TL_BACK6                    1372
#define IDC_ID                          1373
#define IDC_SPIN_MT1                    1373
#define IDC_CODE                        1374
#define IDC_SPIN_MT2                    1374
#define IDC_AUTH                        1375
#define IDC_SPIN_MT3                    1375
#define IDC_SPIN_MT4                    1376
#define IDC_SERIAL                      1376
#define IDC_SPIN_MT5                    1377
#define IDC_AUTHCODE_EDIT               1377
#define IDC_SPIN_MT6                    1378
#define IDC_ATT_START_SPIN              1379
#define IDC_ATT_OFFSET_SPIN             1380
#define IDC_SM_UTILE                    1380
#define IDC_ATT_V1_SPIN                 1381
#define IDC_SM_VIEW                     1382
#define IDC_ATT_V2_SPIN                 1382
#define IDC_SM_RADIUS                   1382
#define IDC_SM_TOOLBAR                  1383
#define IDC_SM_ANGLE                    1383
#define IDC_SM_RESET                    1384
#define IDC_ATT_START                   1385
#define IDC_ATT_OFFSET                  1386
#define IDC_ATT_V1                      1387
#define IDC_ATT_V2                      1388
#define IDC_CC_X                        1390
#define IDC_CC_XSPIN                    1391
#define IDC_CC_XLABEL                   1392
#define IDC_CC_YLABEL                   1393
#define IDC_STATIC_ALIG                 1394
#define IDC_STATIC_SM                   1395
#define IDC_STATIC_FS                   1396
#define IDC_MM_TOOLBAR                  1397
#define IDC_STATIC_FFM                  1398
#define IDC_TL_GROUP_NAME               1398
#define IDC_TL_SETNUMPOINTS             1400
#define IDC_ALLU                        1401
#define IDD_MAP_ACQUIRETL               1401
#define IDC_ALLV                        1402
#define IDC_TL_GMCOL                    1404
#define IDC_ATT_CEN                     1404
#define IDC_TL_GMCOL_SPIN               1405
#define IDC_ATT_CEN_SPIN                1405
#define IDC_ATT_GRAPH                   1406
#define IDC_TL_SHAPE                    1406
#define IDC_TL_RESTO                    1407
#define IDC_FFM_NUMPOINTS               1407
#define IDC_STATIC_SM_NOR               1409
#define IDC_STATIC_SM_LC                1410
#define IDC_MM_TYPE                     1411
#define IDC_DO_APPLYXYZ                 1412
#define IDC_DO_UVWALL                   1413
#define IDC_DO_GIZMO                    1414
#define IDC_TLO_COMPACT_TVERTS          1415
#define IDC_ATTCH_EDIT                  1416
#define IDC_ATT_GROUP_MAP               1416
#define IDC_ATTCH_SPIN                  1417
#define IDC_ATT_GROUP_MAP_SPIN          1417
#define IDC_ATTCEN_EDIT                 1418
#define IDC_ATTCEN_SPIN                 1419
#define IDC_ATTSTR_EDIT                 1420
#define IDC_ATTSTR_SPIN                 1421
#define IDC_ATTOFF_EDIT                 1422
#define IDC_ATTOFF_SPIN                 1423
#define IDC_ATTIN_EDIT                  1424
#define IDC_ATTIN_SPIN                  1425
#define IDC_ATTOUT_EDIT                 1426
#define IDC_ATTOUT_SPIN                 1427
#define IDC_ATT_FACE                    1432
#define IDC_ATT_MOD                     1433
#define IDC_ATT_UVNOT                   1435
#define IDC_ATT_TOP                     1436
#define IDC_ATT_BOTT                    1437
#define IDC_ATT_CURVE                   1438
#define IDC_DC_MAPTYPE                  1441
#define IDC_TXT_HEIGHT                  1442
#define IDC_AQ_ANI                      1443
#define IDC_TXT_HEIGHT2                 1443
#define IDC_ACQUIRE_RELTL               1444
#define IDC_ACQUIRE_ABSTL               1445
#define IDC_MM_ORCH                     1446
#define IDC_MM_ORCHSPIN                 1447
#define IDC_VW                          1449
#define IDC_WU                          1450
#define IDC_UV                          1451
#define IDC_SM_PL                       1452
#define IDC_SM_FL                       1454
#define IDC_SM_CEN                      1455
#define IDC_FFM_TEXT                    1456
#define IDC_ABOUT_BUTTON                1459
#define IDC_LEYENDA                     1460
#define IDC_STATIC_MAP                  1461
#define IDC_LEYENDA2                    1461
#define IDC_STATIC_AUTH                 1462
#define IDC_ID_EDIT                     1465
#define IDC_SERIAL_EDIT                 1466
#define IDC_TL_CURCH_SPIN               1467
#define IDC_TL_SETNUMBER                1468
#define IDC_TL_NUM_CHS                  1469
#define IDC_TLM_TYPES                   1470
#define IDC_TL_CURCH                    1471
#define IDC_TL_LENGTH                   1472
#define IDC_TL_WIDTH                    1473
#define IDC_TL_LENGTH_SPIN              1474
#define IDC_TL_HEIGHT                   1475
#define IDC_TL_WIDTH_SPIN               1476
#define IDC_TL_US                       1477
#define IDC_TL_HEIGHT_SPIN              1477
#define IDC_TL_US_SPIN                  1478
#define IDC_TL_MAPCH                    1478
#define IDC_TL_UO                       1479
#define IDC_TL_MAPCH_SPIN               1479
#define IDC_TL_UO_SPIN                  1480
#define IDC_TL_VO_SPIN                  1481
#define IDC_TL_VO                       1482
#define IDC_TL_VS_SPIN                  1483
#define IDC_TL_VS                       1484
#define IDC_TL_WO_SPIN                  1485
#define IDC_TL_WO                       1486
#define IDC_TL_WS_SPIN                  1487
#define IDC_TL_WS                       1488
#define IDC_TL_ATT_SPIN                 1489
#define IDC_TL_ATT                      1490
#define IDC_TL_ATTON                    1491
#define IDC_TL_AUO_SPIN                 1492
#define IDC_TL_AUO                      1493
#define IDC_TL_AUS_SPIN                 1494
#define IDC_TL_AUS                      1495
#define IDC_TL_AVO_SPIN                 1496
#define IDC_TL_AVO                      1497
#define IDC_TL_AVS_SPIN                 1498
#define IDC_TL_LABEL1                   1499
#define IDC_TL_AVS                      1499
#define IDC_MM_B                        1500
#define IDC_TL_AWS                      1500
#define IDC_MM_A                        1501
#define IDC_TL_AWS_SPIN                 1501
#define IDC_MM_A2                       1502
#define IDC_TL_AWO                      1502
#define IDC_TL_AWO_SPIN                 1503
#define IDC_TL_RUV                      1504
#define IDC_TL_SETNUM                   1505
#define IDC_TL_NUMMAPSSPIN              1505
#define IDC_TL_RUV_SPIN                 1505
#define IDC_TLO_X                       1506
#define IDC_TL_MOVE_U                   1506
#define IDC_TL_LABEL2                   1507
#define IDC_TLO_Y                       1507
#define IDC_TL_SCALE_U                  1507
#define IDC_TLO_Z                       1508
#define IDC_TL_MOVE_V                   1508
#define IDC_TL_LABEL3                   1509
#define IDC_TLS_REVERSE                 1509
#define IDC_TL_SCALE_V                  1509
#define IDC_TLS_NORMALIZED              1510
#define IDC_TL_MOVE_W                   1510
#define IDC_TL_LABEL4                   1511
#define IDC_TLS_PLANE                   1511
#define IDC_TL_SCALE_W                  1511
#define IDC_TLS_CENTER                  1512
#define IDC_TL_MOVE_U_SPIN              1512
#define IDC_TL_LABEL5                   1513
#define IDC_TLS_FIELD                   1513
#define IDC_TL_SCALE_U_SPIN             1513
#define IDC_TLS_PICK_NODE               1514
#define IDC_TL_MOVE_V_SPIN              1514
#define IDC_TL_LABEL6                   1515
#define IDC_TLS_RESET_SPLINE            1515
#define IDC_TL_SCALE_V_SPIN             1515
#define IDC_TLS_UTILE                   1516
#define IDC_TL_MOVE_W_SPIN              1516
#define IDC_TLS_ANGLE                   1517
#define IDC_TL_SCALE_W_SPIN             1517
#define IDC_TLS_RADIUS                  1518
#define IDC_TL_ROT_U                    1518
#define IDC_TLF_NUMPOINTS               1519
#define IDC_TL_ROT_V                    1519
#define IDC_TLF_SET_NUM_POINTS          1520
#define IDC_TL_ROT_W                    1520
#define IDC_TL_TEX1                     1521
#define IDC_TLF_ALLU                    1521
#define IDC_TL_ROT_U_SPIN               1521
#define IDC_TL_TEX2                     1522
#define IDC_TLF_ALLV                    1522
#define IDC_TL_ROT_V_SPIN               1522
#define IDC_TL_TEX3                     1523
#define IDC_TLF_THRESH_SPIN             1523
#define IDC_TL_ROT_W_SPIN               1523
#define IDC_TL_TEX4                     1524
#define IDC_TLF_THRESH                  1524
#define IDC_TL_XF_TO_ATT                1524
#define IDC_TL_TEX5                     1525
#define IDC_TLF_PICK_SURFACE            1525
#define IDC_TLP_B                       1525
#define IDC_TL_TEX6                     1526
#define IDC_ATT_USEMOD                  1526
#define IDC_TLP_B_SPIN                  1526
#define IDC_TLP_FRAME                   1527
#define IDC_TLP_FRAME_SPIN              1528
#define IDC_TLP_ITER                    1529
#define IDC_TLP_ITER_SPIN               1530
#define IDC_TLP_K_SPIN                  1531
#define IDC_TLP_K                       1532
#define IDC_PELT_TOOLBAR                1533
#define IDC_PELT_VIEW                   1534
#define IDC_TLP_EDIT_FRAME              1535
#define IDC_TLP_RESET_FRAME             1536
#define IDC_TLP_MOVE_BORDER             1537
#define IDC_TLP_SAVE_FRAME              1538
#define IDC_MM_GET_SETS                 1538
#define IDC_TLP_LOAD_FRAME              1539
#define IDC_TLFR_PICK_FRAME             1539
#define IDC_TLS_BELT                    1540
#define IDC_TLS_NORMAL_START            1541
#define IDC_TLS_NORMAL_START_SPIN       1542
#define IDC_TLO_SS_EDGES                1544
#define IDC_TLO_SS_FACES                1545
#define IDC_TLD_LOAD                    1545
#define IDC_TLD_SAVE                    1546
#define IDC_TLO_SAVE_CH_UVW             1547
#define IDC_CLOSE                       1548
#define IDC_TLO_CHANNEL                 1549
#define IDC_TLO_CHANNEL_SPIN            1550
#define IDC_TXT_LENGTH                  1551
#define IDC_ACQUIRE_REL                 1552
#define IDC_TXT_WIDTH                   1552
#define IDC_ACQUIRE_ABS                 1553
#define IDC_GROUPS                      1553
#define IDC_TLA_ABOUT                   1555
#define IDC_TLC_ABOUT                   1556
#define IDC_TLON1                       1640
#define IDC_TLON2                       1641
#define IDC_TLON3                       1642
#define IDC_TLON4                       1643
#define IDC_TLON5                       1644
#define IDC_TLON6                       1645
#define IDC_TL_USEIDS                   1646
#define IDC_TL_FACEAT1                  1647
#define IDC_TL_FACEAT2                  1648
#define IDC_TL_FACEAT3                  1649
#define IDC_TL_FACEAT4                  1650
#define IDC_TL_FACEAT5                  1651
#define IDC_TL_FACEAT6                  1652
#define IDC_TL_MODAT1                   1653
#define IDC_TL_MODAT2                   1654
#define IDC_TL_MODAT3                   1655
#define IDC_TL_MODAT4                   1656
#define IDC_TL_MODAT5                   1657
#define IDC_TL_MODAT6                   1658
#define IDC_TL_USEMOD1                  1659
#define IDC_TL_USEMOD2                  1660
#define IDC_TL_USEMOD3                  1661
#define IDC_TL_USEMOD4                  1662
#define IDC_TL_USEMOD5                  1663
#define IDC_TL_USEMOD6                  1664
#define IDC_MAPON                       1711
#define IDS_DS_BITMAP_PARAMS            10131
#define IDS_DS_BITMAP_TEXTURE_ERR       10172
#define IDS_DC_APPARATUS                30015
#define IDS_DC_PARAMETERS               30028
#define IDS_RB_WIDTH                    30039
#define IDS_RB_HEIGHT                   30040
#define IDS_DC_TEXTURELAYERS            30298
#define IDS_MM_TLMOD                    30577
#define IDS_DC_TEXLAYERS                30578
#define IDS_MM_CLASS                    40037
#define IDS_RB_LENGTH                   40353
#define IDS_DC_MULTICOMP                40354
#define IDS_DC_TL                       40354
#define IDS_DC_TLPARAMS                 40355
#define IDS_DC_PICKSPLINE               40356
#define IDC_TL_UP                       40357
#define IDC_TL_PAGEUP                   40358
#define IDC_TL_DOWN                     40359
#define IDC_TL_PAGEDOWN                 40360
#define IDS_MM_SELECTIMAGE              40362
#define IDS_MM_LAYNUM                   40363
#define IDS_DC_DEFTL                    40364
#define IDS_ILLEGALSPLINE               40365
#define IDS_SPLINEMAPPING               40366
#define IDS_PICKSPLINE                  40367
#define IDS_CC_MOVE                     40368
#define IDS_CC_ADD                      40369
#define IDS_CC_DEL                      40370
#define IDS_CC_RESET                    40371
#define IDS_CC_BEZ                      40372
#define IDS_CC_CORN                     40373
#define IDS_CC_LINE                     40374
#define IDS_CC_PAN                      40375
#define IDS_CC_ZE                       40376
#define IDS_CC_ZHE                      40377
#define IDS_CC_ZVE                      40378
#define IDS_CC_ZOOM                     40379
#define IDS_CC_ZOOMX                    40380
#define IDS_CC_ZOOMY                    40381
#define IDS_TL_FILE                     40382
#define IDS_TL_SAVECURTITLE             40383
#define IDS_TL_FILEEXISTS               40384
#define IDS_SAVE_CUR                    40385
#define IDS_SAVE_ALL                    40386
#define IDS_LOAD_ALL                    40387
#define IDS_LOAD_CUR                    40388
#define IDS_LOAD_MERGE                  40389
#define IDS_CUT                         40390
#define IDS_COPY                        40391
#define IDS_PASTE                       40392
#define IDS_PREVIEW                     40393
#define IDS_DC_PICKFFG                  40394
#define IDS_DC_CONTPOINTS               40395
#define IDS_MTL_PICKSPLINE              40396
#define IDS_TL_NONE                     40397
#define IDS_TL_SAVEALLTITLE             40398
#define IDS_TL_MERGETITLE               40399
#define IDS_TL_REPLACEALLTITLE          40400
#define IDS_TL_REPLACECURTITLE          40401
#define IDS_BACK_ALL                    40402
#define IDS_BACK_TOP                    40403
#define IDS_BACK_BOT                    40404
#define IDS_BACK_GRF                    40405
#define IDS_PREVIEW_CURR                40406
#define IDS_PREVIEW_ALL                 40407
#define IDS_UVWPROY_CLASS               40408
#define IDS_DC_UVWPROY                  40409
#define IDS_DC_SELFACES                 40410
#define IDS_DC_MOUSE_ADD                40411
#define IDS_DC_MOUSE_SUBTRACT           40412
#define IDS_DC_MOUSE_SELECTTRI          40413
#define IDS_DC_MOUSE_SELECTFACE         40414
#define IDS_DC_ATTMAP                   40415
#define IDS_DC_ATTPARAMS                40416
#define IDS_DS_RED                      40417
#define IDS_DS_GREEN                    40418
#define IDS_DS_BLUE                     40419
#define IDS_JW_MAP1                     40420
#define IDS_JW_MAP1ENABLE               40421
#define IDS_DS_COLOR1                   40422
#define IDS_DS_COLOR2                   40423
#define IDS_DS_COLOR3                   40424
#define IDS_DS_MAP                      40425
#define IDS_DC_ATTMAP_CDESC             40426
#define IDS_DC_MOUSE_EDGES_ADD          40427
#define IDS_DC_CANAL                    40428
#define IDS_MAPTYPE_PLANAR              40429
#define IDS_MAPTYPE_CYL                 40430
#define IDS_MAPTYPE_CYLCAP              40431
#define IDS_MAPTYPE_SPHERE              40432
#define IDS_MAPTYPE_SHRINK              40433
#define IDS_MAPTYPE_BOX                 40434
#define IDS_MAPTYPE_FACE                40435
#define IDS_MAPTYPE_XYZ                 40436
#define IDS_MAPTYPE_SPLINE              40437
#define IDS_MAPTYPE_FFM                 40438
#define IDS_MAPTYPE_DATA                40439
#define IDS_MAPTYPE_DATA1               40440
#define IDS_MAPTYPE_DATA2               40441
#define IDS_MAPTYPE_DATA3               40442
#define IDS_MAPTYPE_DATA4               40443
#define IDS_MAPTYPE_DATA5               40444
#define IDS_DC_POINT                    40445
#define IDS_DC_INVEC                    40446
#define IDS_DC_OUTVEC                   40447
#define IDS_GRIDMESH_CLASS              40448
#define IDS_DC_HEIGHT                   40449
#define IDS_DC_RADIUS                   40450
#define IDS_PARAMETERS                  40451
#define IDS_SIMPLE                      40452
#define IDS_TL_TILE_U                   40453
#define IDS_TL_TILE_V                   40454
#define IDS_TL_TILE_W                   40455
#define IDS_TL_OFFSET_U                 40456
#define IDS_TL_OFFSET_V                 40457
#define IDS_TL_OFFSET_W                 40458
#define IDS_TL_LENGTH                   40459
#define IDS_TL_WIDTH                    40460
#define IDS_TL_HEIGHT                   40461
#define IDS_TL_ATT_ON                   40462
#define IDS_TL_ATT_U_S                  40463
#define IDS_TL_ATT_U_O                  40464
#define IDS_TL_ATT_V_S                  40465
#define IDS_TL_ATT_V_O                  40466
#define IDS_TL_ATT_W_S                  40467
#define IDS_TL_ATT_W_O                  40468
#define IDS_TL_ATT_RUV                  40469
#define IDS_TL_FFM_THRESH               40470
#define IDS_TL_MODNAME                  40471
#define IDS_TL_SELECTIMAGE              40472
#define IDS_TL_PARAMETERS               40473
#define IDS_TLF_PICK_SURFACE            40474
#define IDS_NOT_AUTH                    40475
#define IDS_ATT_TEXLAY_MOD              40476
#define IDS_ATT_MAP_CHANNEL             40477
#define IDS_TL_U_MOVE                   40478
#define IDS_TL_V_MOVE                   40479
#define IDS_TL_W_MOVE                   40480
#define IDS_TL_U_SCALE                  40481
#define IDS_TL_V_SCALE                  40482
#define IDS_TL_W_SCALE                  40483
#define IDS_MAPTYPE_PELT                40484
#define IDS_DC_SELEDGES                 40485
#define IDS_DC_MOUSE_EDGES_SUBTRACT     40486
#define IDS_DC_MOUSE_SELECTEDGE         40487
#define IDS_TL_PELT_K                   40488
#define IDS_TL_PELT_B                   40489
#define IDS_TL_PELT_FRAME               40490
#define IDS_TL_PELT_ITER                40491
#define IDS_TLP_ADDPT                   40492
#define IDS_TLP_DELPT                   40493
#define IDS_PELT_VIEW_CLASS             40494
#define IDS_TLP_MOVE                    40495
#define IDS_TLP_MOVE_X                  40496
#define IDS_TLP_MOVE_Y                  40497
#define IDS_TLP_PAN                     40498
#define IDS_TLP_ZOOM                    40499
#define IDS_TLP_ZOOMEXT                 40500
#define IDS_PELT_MOVEPOINTS             40501
#define IDS_PELT_FRAME                  40502
#define IDS_TLP_SAVE_FRAME              40503
#define IDS_TLP_LOAD_FRAME              40504
#define IDS_PELT_FRAME_FILE             40505
#define IDS_TLFR_PICKFRAME              40506
#define IDS_TLFR_ILLEGAL_FRAME          40507
#define IDS_TLFR_FRAME                  40508
#define IDS_MAPTYPE_FRAME               40509
#define IDS_TL_U_ROTATE                 40510
#define IDS_TL_V_ROTATE                 40511
#define IDS_TL_W_ROTATE                 40512
#define IDS_PELT_SYMM                   40513
#define IDS_PELT_SYMM_X                 40514
#define IDS_PELT_SYMM_Y                 40515
#define IDS_PELT_ROTP90                 40516
#define IDS_PELT_ROTN90                 40517
#define IDS_PELT_ROT180                 40518
#define IDS_TLP_SYMMPAIR                40519
#define IDS_TL_SPL_NORMALS_START        40520
#define IDS_ADD_GROUP                   40521
#define IDS_DEL_GROUP                   40522
#define IDS_TOOLS                       40523
#define IDS_TL2_UVWFILES                40524
#define IDS_TL2_SAVEOBJECT              40525
#define IDS_TL2_FILEEXISTS              40526
#define IDS_TLP_SCALE                   40527
#define IDS_TLP_SCALE_X                 40528
#define IDS_TLP_SCALE_Y                 40529
#define IDS_TLP_ROTATE                  40530
#define IDS_PELT_ROTATEPOINTS           40531
#define IDS_PELT_SCALEPOINTS            40532
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1557
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
